import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";
import remarkSmartypants from "remark-smartypants";
import { rehypeHonorific } from "./src/plugins/rehype-honorific";
import { remarkAbbr } from "./src/plugins/remark-abbr";

const articlesDir = fileURLToPath(new URL("../../data/articles", import.meta.url));
const articleDates: Record<string, string> = {};
try {
	for (const file of readdirSync(articlesDir).filter((f) => f.endsWith(".md"))) {
		const content = readFileSync(join(articlesDir, file), "utf-8");
		const match = content.match(/publishedAt:\s*"([^"]+)"/);
		if (match) {
			articleDates[file.replace(/\.md$/, "")] = match[1];
		}
	}
} catch {
	// articles dir may not exist during first build
}

// 301 redirects for old WordPress URLs → homepage (preserves SEO on same domain)
// Pages with actual content on the new site are excluded.
const legacyRedirects: Record<string, { status: 301; destination: string }> = {};
const oldPaths = [
	// Posts (islam/)
	"/islam/liknelsen-for-den-fastande-ar-en-man-som-bar-pa-en-sack-mysk",
	"/islam/jag-har-delat-bonen-mellan-mig-och-min-tjanare",
	"/islam/en-grundlaggande-forklaring-av-koranens-forsta-kapitel-al-fatihah",
	"/islam/sara-varfor-jag-bar-sloja",
	"/islam/jenny-jag-angrar-inte-min-sjal",
	"/islam/rabia-vad-jag-tycker-om-min-sjal",
	"/islam/johara-att-bara-sloja-under-en-dag",
	"/islam/annica-folk-visar-mig-mer-respekt",
	"/islam/ahmad-ibn-hanbal",
	"/islam/ibn-taymiyyah",
	"/islam/muhammad-ibn-ismail-al-bukhari",
	"/islam/ramadan",
	"/islam/ingen-gud-utom-gud",
	"/islam/guds-attribut",
	"/islam/slojan-i-koranen",
	"/islam/tafsir",
	"/islam/fastans-inre-hemligheter",
	"/islam/fasta-under-graviditeten",
	"/islam/ingen-finns-som-kan-liknas-vid-honom",
	"/islam/dawah",
	"/islam/islams-troslara",
	"/islam/tron-pa-gud",
	"/islam/tron-pa-skrifterna",
	"/islam/tron-pa-sandebuden",
	"/islam/tron-pa-den-yttersta-dagen",
	"/islam/islams-behorighetskrav",
	"/islam/ar-islam-fatalistiskt",
	"/islam/ar-det-sant-att-muhammad-ma-guds-frid-och-valsignelser-vara-over-honom-skrev-koranen",
	"/islam/hur-skiljer-sig-koranen-fran-de-andra-skrifterna",
	"/islam/motsager-islam-vetenskap",
	"/islam/koranen-namner-att-manniskan-skapats-fran-jordstoff-men-den-namner-ocksa-att-hon-skapats-av-sadesvatska-ar-inte-detta-motsagelsefullt",
	"/islam/varfor-alagger-islam-sa-stranga-straff-for-utomaktenskapliga-forbindelser",
	"/islam/ar-islam-en-militant-religion",
	"/islam/koranen-sager-att-muslimer-skall-drapa-de-som-inte-tror-varhelst-de-finner-dem-betyder-detta-att-islam-stodjer-vald-och-blodspillan",
	"/islam/alla-religioner-lar-i-grund-och-botten-dess-anhangare-att-vara-goda-sa-varfor-skall-man-folja-just-islam",
	"/islam/ahlus-sunnah",
	"/islam/se-i-paradiset",
	"/islam/muslimer-svaga",
	"/islam/jan-malmsjo-talar-om-islam",
	"/islam/tron-pa-skrifterna-som-gud-sant-ned",
	"/islam/tron-pa-guds-anglar",
	"/islam/guds-profeter",
	"/islam/ateruppstandelsens-dag",
	"/islam/tron-pa-det-forutbestamda",
	"/islam/en-kar-mormor",
	"/islam/allah-eller-gud",
	"/islam/foraldrar",
	"/islam/kazakstans-matkultur",
	"/islam/afghanistans-matkultur",
	"/islam/malaysias-matkultur",
	"/islam/indonesiens-matkultur",
	"/islam/barns-rattigheter",
	"/islam/existensialism",
	"/islam/karma",
	"/islam/hinduismens-kastsystem",
	"/islam/hinduismens-manga-gudar",
	"/islam/antropomorfism",
	"/islam/religionernas-olika-namn",
	"/islam/ett-liv-utan-religion",
	"/islam/sjalens-existens-2",
	"/islam/balans-mellan-yttre-och-inre-valbefinnande",
	// Posts (featured/)
	"/featured/celler-och-stjarnor",
	"/featured/planeterna-i-solsystemet",
	"/featured/mangudemyten",
	"/featured/personlig-utveckling",
	"/featured/somnbrist",
	"/featured/meningen-med-livet",
	"/featured/en-gang-kom-en-okenbo-till-profeten-fred-vare-med-honom",
	"/featured/en-levande-planet-2",
	"/featured/fastans-historiska-anknytning",
	"/featured/omsesidig-karlek",
	// Posts (uncategorized/)
	"/uncategorized/terrorism",
	"/uncategorized/skapad-av-sadesvatska",
	"/uncategorized/vad-kvinnans-skote-doljer",
	"/uncategorized/religionens-ursprung",
	"/uncategorized/avgora-barnets-kon",
	"/uncategorized/orsak-och-verkan-varden",
	"/uncategorized/sitemap",
	"/uncategorized/bonetider",
	"/uncategorized/forsta-skyldigheten-som-aligger-manniskan",
	"/uncategorized/evolutio",
	"/uncategorized/forberedelser-infor-bonen-2",
	"/uncategorized/sa-blir-du-muslim-2",
	"/uncategorized/naderik-eller-bestraffande",
	// Posts (utvalda/)
	"/utvalda/fakta-om-islam",
	// Posts (other prefixes)
	"/tro/gud",
	"/tro/sandebuden-och-skrifterna",
	"/tro/sjalens-existens",
	"/tro/anglarna",
	"/tro/livet-efter-doden",
	"/tro/en-medelvag-mellan-tro-och-handling",
	"/tro/profeten-muhammed",
	"/tro/domedagen",
	"/tro/odet",
	"/tro/koranen",
	"/tro/forklaring-av-trosbekannelserna",
	"/kost/omskarelse",
	"/kost/amning",
	"/kost/rokning",
	"/kost/traning",
	"/kost/griskott",
	"/kost/muslimsk-matkultur-i-historien",
	"/kost/medicinska-anledningar-for-alkoholforbud",
	"/kost/utbrandhet",
	"/kost/inre-och-yttre-valbefinnande",
	"/kost/partnerskapet-mellan-kropp-och-sjal",
	"/kost/halalslakt",
	"/kost/mediciner",
	"/kost/vinager",
	"/gud/kunskap-om-guds-namn-och-attribut",
	"/gud/kalla-gud-for-han",
	"/gud/guds-harstamning",
	"/gud/verklig-kunskap-om-gud",
	"/gud/hur-manga-skapare-finns-det",
	"/gud/gud-skapar-men-manniskan-omvandlar",
	"/gud/gud-ar-skild-fran-skapelsen",
	"/gud/kan-gud-fa-en-son",
	"/gud/en-existens-tyder-pa-att-det-ocksa-finns-en-skapare",
	"/gud/gud-beskriver-sig-sjalv",
	"/gud/en-personlig-eller-icke-personlig-gud",
	"/gud/intellektets-begransningar",
	"/gud/big-bang",
	"/gud/argument-for-guds-existens",
	"/gud/allsmaktighetsparadoxen",
	"/gud/treenigheten",
	"/gud/anledning-till-att-vi-dyrkar-allah",
	"/gud/monoteism",
	"/gud/guds-namn",
	"/jihad/islam-spreds-inte-med-svardet",
	"/jihad/manniskors-lika-varde",
	"/jihad/misstolkade-koranverser",
	"/jihad/tvang-skall-inte-forekomma",
	"/jihad/samexistens-och-tolerans",
	"/jihad/mer-an-ett-heligt-krig",
	"/jihad/en-avslappnad-installning",
	"/jihad/jihad",
	"/jihad/attacker-mot-civila-under-jihad",
	"/jihad/extremism",
	"/jihad/terrorism-2",
	"/kvinna/abort",
	"/kvinna/kvinnlig-omskarelse-konsstympning",
	"/kvinna/modern-har-tre-rattigheter",
	"/kvinna/graviditet-ar-inte-ett-bevis",
	"/kvinna/kvinnans-mindre-arv",
	"/kvinna/kan-kvinnan-ha-flera-man",
	"/kvinna/kvinnofortryck",
	"/kvinna/vad-onskar-den-muslimska-kvinnan",
	"/kvinna/hedersrelaterat-vald",
	"/kvinna/temporara-aktenskap",
	"/kvinna/polygami-polygyni-polyandri",
	"/kvinna/hedersmord",
	"/kvinna/slojan",
	"/kvinna/kvinnosyn",
	"/kvinna/jamstalldhet",
	"/kvinna/fyra-vittnen-till-en-valdtakt",
	"/kvinna/tvangsaktenskap",
	"/kvinna/frun-foder-en-dotter",
	"/historia/ett-vetenskapligt-synsatt",
	"/historia/uthmans-kalifat",
	"/historia/uppenbarelsens-borjan",
	"/historia/rasism-och-fordomar-i-historien",
	"/historia/islamisk-ekonomi",
	"/historia/symboler",
	"/historia/emigrationen-till-medina",
	"/historia/erovringen-av-mecka",
	"/historia/abu-bakrs-och-umars-kalifat",
	"/historia/indien-malaysia-indonesien",
	"/historia/det-muslimska-arvet-i-spanien",
	"/historia/vetenskap-i-den-islamiska-varlden-under-medeltiden",
	"/historia/kultur-som-undervarderar-vetenskap",
	"/historia/den-islamiska-varlden-bilder",
	"/religion/filosofernas-gudssyn",
	"/religion/spadomar-och-horoskop",
	"/religion/religionen-i-historien",
	"/religion/kriterier-for-en-sann-religion",
	"/religion/en-kategorisering-av-varldsreligionerna",
	"/religion/alla-religioner-sager-sig-vara-den-ratta",
	"/religion/deism-och-sekularism",
	"/religion/mysticism",
	"/religion/anledningar-till-att-religionen-avvisats",
	"/religion/i-sjalen-medfott",
	"/religion/behovet-av-religion",
	"/religion/ateism",
	"/religion/vagarna-till-sann-religion",
	"/religion/sufism",
	"/religion/shia",
	"/religion/jesus",
	"/religion/vidskepelse",
	"/religion/overallt-och-alltid-for-alla",
	"/religion/pandoras-ask",
	"/religion/agnosticism",
	"/religion/skillnader-mellan-religion-och-vetenskap",
	"/religion/kristendomens-gudssyn",
	"/religion/judendomens-gudssyn",
	"/religion/islams-gudssyn",
	"/religion/de-flesta-har-trott-pa-gud",
	"/existens/universums-ursprung",
	"/existens/hur-manniskan-skapar",
	"/existens/en-levande-planet",
	"/existens/manniskans-plats-i-universum",
	"/existens/syftet-med-skapelsen-av-manniskoslaktet",
	"/existens/konstverket-ar-inte-konstnaren",
	"/pelare/dyrkan",
	"/pelare/hogtider",
	"/pelare/sharia",
	"/pelare/trosbekannelsen",
	"/pelare/sunna",
	"/pelare/mosken",
	"/pelare/bonen",
	"/pelare/allmosan",
	"/pelare/vallfarden",
	"/pelare/ramadan-2",
	"/guider/sa-blir-du-muslim",
	"/guider/forberedelser-infor-bonen",
	"/guider/lar-dig-be",
	"/guider",
	// Pages
	"/vetenskap",
	"/historia",
	"/trosartiklar",
	"/universum",
	"/livsaskadning",
	"/gudssyn",
	"/islam-i-praktik/konvertera",
	"/islam-i-praktik",
	"/islam-i-praktik/tvagningen",
	"/islam-i-praktik/ghusl",
	"/islam-i-praktik/nar-tvagning-kravs",
	"/islam-i-praktik/video-tvagningen",
	"/islam-i-praktik/video-bonen",
	"/islam-i-praktik/odmjukhet-under-bonen",
	"/islam-i-praktik/boneguide",
	"/halsa",
	"/arbete",
	"/arbete/salja-varor-till-olika-priser",
	"/arbete/arbete-och-valstand",
	"/arbete/strejker",
	"/vetenskap/att-soka-den-absoluta-sanningen-i-vetenskap",
	"/vetenskap/embryologi",
	"/portfolio",
	"/andra-religioners-syn-pa-gud",
	"/livsaskadning/genomgang",
	"/om/forslag",
	"/om/rattigheter",
	"/om/kontakt",
	"/om/om-islam-se",
	"/om/integritet",
	// Categories
	"/category/polare-1a",
	"/category/existens",
	"/category/featured",
	"/category/gud",
	"/category/guider",
	"/category/historia",
	"/category/jihad",
	"/category/kost",
	"/category/kvinna",
	"/category/nytt",
	"/category/islam",
	"/category/polare",
	"/category/religion",
	"/category/tro",
	"/category/uncategorized",
	"/category/utvalda",
	"/category/faq",
	"/category/xslider",
	// Tags
	"/tag/bonetid",
	"/tag/bonetider",
	"/tag/faste-tider",
	"/tag/fastetider",
	"/tag/ramadankalender",
	"/tag/ramdan-tidtabell",
	// Authors
	"/author/dr-abdullah-s-ash-shehri",
	"/author/muhammad-bin-salih-al-uthaymin",
	"/author/admin",
	"/author/knut",
];

for (const path of oldPaths) {
	legacyRedirects[path] = { status: 301, destination: "/" };
}

export default defineConfig({
	site: "https://islam.se",
	output: "static",
	redirects: legacyRedirects,
	prefetch: { defaultStrategy: "hover" },
	build: { inlineStylesheets: "always" },
	markdown: {
		remarkPlugins: [
			[
				remarkSmartypants,
				{
					openingQuotes: { double: "»", single: "\u2019" },
					closingQuotes: { double: "«", single: "\u2019" },
					dashes: "oldschool",
				},
			],
			remarkAbbr,
		],
		rehypePlugins: [rehypeHonorific],
	},
	fonts: [
		{
			provider: fontProviders.local(),
			name: "Literata",
			cssVariable: "--font-body",
			fallbacks: ["Georgia", "Times New Roman", "serif"],
			options: {
				variants: [
					{
						weight: "200 900",
						style: "normal",
						src: ["./src/assets/fonts/literata-roman.woff2"],
					},
					{
						weight: "200 900",
						style: "italic",
						src: ["./src/assets/fonts/literata-italic.woff2"],
					},
				],
			},
		},
		{
			provider: fontProviders.local(),
			name: "Source Sans 3",
			cssVariable: "--font-heading",
			fallbacks: ["system-ui", "sans-serif"],
			options: {
				variants: [
					{
						weight: "200 900",
						style: "normal",
						src: ["./src/assets/fonts/source-sans-3-roman.woff2"],
					},
				],
			},
		},
	],
	integrations: [
		sitemap({
			filter: (page) => !oldPaths.some((p) => page.endsWith(`${p}/`) || page.endsWith(p)),
			serialize(item) {
				const slug = item.url.replace("https://islam.se/", "").replace(/\/$/, "");
				if (articleDates[slug]) {
					item.lastmod = new Date(articleDates[slug]).toISOString();
				}
				return item;
			},
		}),
	],
});
