/**
 * rehype-quran-verse: wherever an essay cites a Quran verse in a footnote
 * ("Koranen, <Name> S:A"), inject a compact recitation player right after the
 * block that carries the citation, sized to blend into the reading flow.
 *
 * The author adds nothing new: they already quote the verse in Swedish and cite
 * it in a footnote. This plugin reads the per-verse data generated by
 * `pnpm sync-verses` (src/data/quran-verses.json: Arabic + al-Nufais mp3 + QUL
 * word timing) and renders the Arabic + a play control as proper hAST. A verse
 * with no generated data (QUL gap / alignment skip) is simply left without a
 * player. The Swedish translation is deliberately omitted — the literary Swedish
 * is already in the prose.
 *
 * Runs as rehype (not remark) so it can read the rendered footnote section: GFM
 * footnote definitions become <li id="user-content-fn-N"> and the inline marks
 * become <a data-footnote-ref href="#user-content-fn-N">. We map each Quran
 * footnote to its ayah, then drop a player after each top-level block that links
 * to one.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { tokenizeArabic } from "../lib/arabic";

interface EssayVerse {
	textArabic: string;
	audioFile: string;
	segments: [number, number, number][];
	reciter: string;
}

// Generated by `pnpm sync-verses`; read defensively so a first build before the
// file exists (or an empty map) degrades to "no players" instead of failing.
const VERSES: Record<string, EssayVerse> = (() => {
	try {
		const path = fileURLToPath(new URL("../data/quran-verses.json", import.meta.url));
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return {};
	}
})();

// Footnote DEFINITION text, e.g. "Koranen, Yūnus 10:36." or "sura al-Baqara 2:255".
// Group 1 is the surah name exactly as the essay writes it (corpus transliteration),
// so the player's citation matches the prose. Mirrors src/lib/citations.ts.
// ⚠️ Group 4 is an optional ayah range. quran-verses.json keys ranges as "23:99-100",
// so without it a footnote reading "23:99–100" resolved to "23:99" and silently found
// no recitation — the attribution-line matcher below has always parsed ranges.
const CITATION =
	/(?:Koranen,\s*|sura\s+)([^\d\n]{0,40}?)\s*(\d{1,3}):(\d{1,3})(?:\s*[–—-]\s*(\d{1,3}))?/;

interface HastText {
	type: "text";
	value: string;
}
interface HastElement {
	type: "element";
	tagName: string;
	properties: Record<string, unknown>;
	children: HastNode[];
}
type HastNode = HastText | HastElement | { type: string; children?: HastNode[] };

const isElement = (n: HastNode): n is HastElement => n.type === "element";
const text = (value: string): HastText => ({ type: "text", value });
const h = (
	tagName: string,
	properties: Record<string, unknown>,
	children: HastNode[] = [],
): HastElement => ({ type: "element", tagName, properties, children });

/** Concatenated text content of a subtree. */
function textOf(node: HastNode): string {
	if (node.type === "text") return (node as HastText).value;
	if ("children" in node && node.children) return node.children.map(textOf).join("");
	return "";
}

const childrenOf = (n: HastNode): HastNode[] => ("children" in n && n.children ? n.children : []);

function isFootnotesSection(n: HastNode): boolean {
	if (!isElement(n) || n.tagName !== "section") return false;
	const cls = n.properties.className;
	return "dataFootnotes" in n.properties || (Array.isArray(cls) && cls.includes("footnotes"));
}

/** Map each footnote id ("user-content-fn-1") to its Quran citation, if any. */
function buildFootnoteMap(section: HastElement): Map<string, { ayahKey: string; refName: string }> {
	const map = new Map<string, { ayahKey: string; refName: string }>();
	const walk = (node: HastNode): void => {
		if (isElement(node) && node.tagName === "li") {
			const id = node.properties.id;
			if (typeof id === "string" && id.includes("fn-")) {
				const m = CITATION.exec(textOf(node));
				if (m) {
					const refName = m[1].trim().replace(/[.,;:]+$/, "");
					map.set(id, { ayahKey: verseKey(m[2], m[3], m[4]), refName });
				}
			}
			return; // definitions don't nest
		}
		for (const c of childrenOf(node)) walk(c);
	};
	walk(section);
	return map;
}

// Any quotation mark. This site renders Swedish guillemets as »opening … closing«;
// curly and straight pairs are included so the gate survives a smartypants change.
const QUOTE_MARK = /[«»“”‘’"']/u;

/** Ayahs (ordered, de-duped) GENUINELY QUOTED inside one top-level block. A footnote
 *  marker annotates the text back to the previous marker (or the block start); the
 *  verse counts as quoted when that span carries a quotation mark — or when the
 *  marker sits inside a blockquote, where the block itself is the quote and no inline
 *  marks appear. A verse merely cited after a paraphrase has no quotation in its span
 *  and is dropped, so no orphan player is injected.
 *
 *  Span-based, not "the character right before the marker": authors often close the
 *  quote and then add an attribution before the marker — »…visar,« säger Koranen.[n]
 *  — and that verse is still quoted. The walk is in document order, so `span` always
 *  holds the text from the previous marker up to the current one; every marker
 *  (Quran or not) closes a span. Only ayahs we have audio for are kept. */
function versesInBlock(
	block: HastNode,
	fnMap: Map<string, { ayahKey: string; refName: string }>,
): { ayahKey: string; refName: string }[] {
	const out: { ayahKey: string; refName: string }[] = [];
	const seen = new Set<string>();
	let span = "";
	let blockquoteDepth = 0;
	const walk = (node: HastNode): void => {
		if (node.type === "text") {
			span += (node as HastText).value;
			return;
		}
		const el = isElement(node) ? node : null;
		if (el?.tagName === "a" && "dataFootnoteRef" in el.properties) {
			const href = el.properties.href;
			const id = typeof href === "string" ? href.replace(/^#/, "") : "";
			const cite = fnMap.get(id);
			const quoted = blockquoteDepth > 0 || QUOTE_MARK.test(span);
			if (cite && VERSES[cite.ayahKey] && !seen.has(cite.ayahKey) && quoted) {
				seen.add(cite.ayahKey);
				out.push(cite);
			}
			span = ""; // the marker closes the span it annotates; skip its digit text
			return;
		}
		if (el?.tagName === "blockquote") blockquoteDepth++;
		for (const c of childrenOf(node)) walk(c);
		if (el?.tagName === "blockquote") blockquoteDepth--;
	};
	walk(block);
	return out;
}

const playIcon = (): HastElement =>
	h(
		"svg",
		{
			className: ["qv-icon-play"],
			width: 13,
			height: 13,
			viewBox: "0 0 18 18",
			fill: "currentColor",
			ariaHidden: "true",
		},
		[h("path", { d: "M4 2.5v13l11-6.5z" })],
	);

const pauseIcon = (): HastElement =>
	h(
		"svg",
		{
			className: ["qv-icon-pause"],
			width: 13,
			height: 13,
			viewBox: "0 0 18 18",
			fill: "currentColor",
			ariaHidden: "true",
		},
		[
			h("rect", { x: 4, y: 2, width: 3.5, height: 14, rx: 0.5 }),
			h("rect", { x: 10.5, y: 2, width: 3.5, height: 14, rx: 0.5 }),
		],
	);

/**
 * The answer pages (data/svar) carry no footnotes — not one of the 63 does. They
 * quote the Qur'an as a blockquote closed by an attribution line:
 *
 *     > SÄG: "Han är Gud – En, …"
 *     > — Koranen 112:1–4
 *
 * so that line is their citation, and matching it is how the same player reaches
 * them. Ranges are ordinary here (a short sura quoted whole) and are supported end
 * to end: `sync-verses` cuts the range as one contiguous span of the reciter's
 * surah master, so the highlight runs straight through it.
 *
 * Mirrors SVAR_ATTRIBUTION in scripts/sync-verses.ts — the set of verses generated
 * and the set injected must stay the same set.
 */
const SVAR_ATTRIBUTION =
	/[—–-]\s*Koranen\s+(\d{1,3}):(\d{1,3})(?:\s*[–—-]\s*(\d{1,3}))?(?:\s*\([^)]*\))?[\s.]*$/;

/** Normalized verse key: "2:255" for a single ayah, "112:1-4" for a range. */
function verseKey(surah: string, from: string, to?: string): string {
	return to && Number(to) > Number(from) ? `${surah}:${from}-${to}` : `${surah}:${from}`;
}

/** Human citation for a key: "112:1–4" (en dash, as the page writes it). */
function citeRange(key: string): string {
	const [surah, ayahs] = key.split(":");
	return `${surah}:${ayahs.replace("-", "–")}`;
}

/** The verse a blockquote attributes itself to, if we have audio for it.
 *
 *  The attribution CLOSES the quote, but it is usually not its own paragraph:
 *  markdown joins consecutive `>` lines into one paragraph separated by a soft
 *  break, so
 *      > SÄG: »Han är Gud – En, …«
 *      > — Koranen 112:1–4
 *  becomes a single <p> whose text carries a newline, while the pages that leave a
 *  blank `>` line get two <p>s. Only 5 of the 51 pages use the second form. So
 *  match the END of the last paragraph rather than the start of a line: that covers
 *  both spellings and any separator, and the `$` anchor is what keeps a "Koranen
 *  2:255" mentioned mid-quotation from being read as an attribution. */
function attributedVerse(block: HastNode): string | null {
	if (!isElement(block) || block.tagName !== "blockquote") return null;
	const paras = childrenOf(block).filter((c) => isElement(c) && c.tagName === "p");
	const last = paras[paras.length - 1];
	if (!last) return null;
	const m = SVAR_ATTRIBUTION.exec(textOf(last).trim());
	if (!m) return null;
	const key = verseKey(m[1], m[2], m[3]);
	return VERSES[key] ? key : null;
}

function buildPlayer(ayahKey: string, refName: string): HastElement {
	const v = VERSES[ayahKey];
	const tokens = tokenizeArabic(v.textArabic);
	const words = tokens.map((t) =>
		t.word === null
			? h("span", { className: ["qv-waqf"] }, [text(`${t.text} `)])
			: h("span", { className: ["qv-w"], dataW: t.word }, [text(`${t.text} `)]),
	);
	const ref = citeRange(ayahKey);
	const nameLabel = refName ? `${refName} ` : "";
	const cite = `Koranen · ${nameLabel}${ref}`;
	return h("figure", { className: ["quran-verse"] }, [
		h(
			"p",
			{
				className: ["qv-arabic"],
				dir: "rtl",
				lang: "ar",
				dataSegments: JSON.stringify(v.segments),
			},
			words,
		),
		h("div", { className: ["qv-meta"] }, [
			h(
				"button",
				{
					type: "button",
					className: ["qv-play"],
					dataAudio: v.audioFile,
					ariaLabel: `Lyssna på ${nameLabel}${ref}, reciterad av ${v.reciter}`,
				},
				[playIcon(), pauseIcon()],
			),
			h("span", { className: ["qv-cite", "label"] }, [text(cite)]),
		]),
	]);
}

export function rehypeQuranVerse() {
	return (tree: HastNode): void => {
		if (!("children" in tree && tree.children)) return;
		const blocks = tree.children;
		const section = blocks.find(isFootnotesSection) as HastElement | undefined;
		// Essays cite in footnotes; answer pages attribute under a blockquote. A
		// document with neither gets no players.
		const fnMap = section ? buildFootnoteMap(section) : new Map();

		const out: HastNode[] = [];
		for (const node of blocks) {
			out.push(node);
			if (node === section || !isElement(node)) continue;

			// A blockquote that names its verse gets the player directly beneath it —
			// the reader has just read the Swedish, and can now hear the Arabic.
			//
			// No surah name here, deliberately. An essay's player takes its name from
			// the essay's own footnote, so it always matches that essay's prose. The
			// answer pages attribute with digits only ("— Koranen 112:1–4"), and the
			// nearest machine source is Tarteel's ASCII transliteration — which would
			// have put "Al-Ma'idah" and "Al-Ahzab" on 51 pages next to essays writing
			// al-Māʾida and al-Aḥzāb. A third transliteration style is worse than no
			// name at all, and the citation is already spelled out one line above.
			const attributed = attributedVerse(node);
			if (attributed) {
				out.push(buildPlayer(attributed, ""));
				continue;
			}

			if (fnMap.size === 0) continue;
			for (const { ayahKey, refName } of versesInBlock(node, fnMap)) {
				out.push(buildPlayer(ayahKey, refName));
			}
		}
		tree.children = out;
	};
}
