/**
 * rehype-quran-verse: wherever an essay cites a Quran verse in a footnote
 * ("Koranen, <Name> S:A"), inject a compact recitation player right after the
 * block that carries the citation — the same word-by-word highlight as the
 * homepage daily verse (§7.2), sized to blend into the reading flow.
 *
 * The author adds nothing new: they already quote the verse in Swedish and cite
 * it in a footnote. This plugin reads the per-verse data generated by
 * `pnpm sync-verses` (src/data/quran-verses.json: Arabic + al-Nufais mp3 + QUL
 * word timing) and renders the Arabic + a play control as proper hAST. A verse
 * with no generated data (QUL gap / alignment skip) is simply left without a
 * player. The Swedish translation and per-word glosses are deliberately omitted —
 * the literary Swedish is already in the prose, and glosses are a homepage-only aid.
 *
 * Runs as rehype (not remark) so it can read the rendered footnote section: GFM
 * footnote definitions become <li id="user-content-fn-N"> and the inline marks
 * become <a data-footnote-ref href="#user-content-fn-N">. We map each Quran
 * footnote to its ayah, then drop a player after each top-level block that links
 * to one.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { tokenizeArabic } from "../lib/arabic";

interface EssayVerse {
	textArabic: string;
	audioFile: string;
	segments: [number, number, number][];
	reciter: string;
}

// Generated by `pnpm sync-verses`; read defensively so a first build before the
// file exists (or an empty map) degrades to "no players" instead of failing.
const VERSES: Record<string, EssayVerse> = (() => {
	try {
		const path = fileURLToPath(new URL("../data/quran-verses.json", import.meta.url));
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return {};
	}
})();

// Footnote DEFINITION text, e.g. "Koranen, Yūnus 10:36." or "sura al-Baqara 2:255".
// Group 1 is the surah name exactly as the essay writes it (corpus transliteration),
// so the player's citation matches the prose. Mirrors src/lib/citations.ts.
const CITATION = /(?:Koranen,\s*|sura\s+)([^\d\n]{0,40}?)\s*(\d{1,3}):(\d{1,3})/;

interface HastText {
	type: "text";
	value: string;
}
interface HastElement {
	type: "element";
	tagName: string;
	properties: Record<string, unknown>;
	children: HastNode[];
}
type HastNode = HastText | HastElement | { type: string; children?: HastNode[] };

const isElement = (n: HastNode): n is HastElement => n.type === "element";
const text = (value: string): HastText => ({ type: "text", value });
const h = (
	tagName: string,
	properties: Record<string, unknown>,
	children: HastNode[] = [],
): HastElement => ({ type: "element", tagName, properties, children });

/** Concatenated text content of a subtree. */
function textOf(node: HastNode): string {
	if (node.type === "text") return (node as HastText).value;
	if ("children" in node && node.children) return node.children.map(textOf).join("");
	return "";
}

const childrenOf = (n: HastNode): HastNode[] => ("children" in n && n.children ? n.children : []);

function isFootnotesSection(n: HastNode): boolean {
	if (!isElement(n) || n.tagName !== "section") return false;
	const cls = n.properties.className;
	return "dataFootnotes" in n.properties || (Array.isArray(cls) && cls.includes("footnotes"));
}

/** Map each footnote id ("user-content-fn-1") to its Quran citation, if any. */
function buildFootnoteMap(section: HastElement): Map<string, { ayahKey: string; refName: string }> {
	const map = new Map<string, { ayahKey: string; refName: string }>();
	const walk = (node: HastNode): void => {
		if (isElement(node) && node.tagName === "li") {
			const id = node.properties.id;
			if (typeof id === "string" && id.includes("fn-")) {
				const m = CITATION.exec(textOf(node));
				if (m) {
					const refName = m[1].trim().replace(/[.,;:]+$/, "");
					map.set(id, { ayahKey: `${m[2]}:${m[3]}`, refName });
				}
			}
			return; // definitions don't nest
		}
		for (const c of childrenOf(node)) walk(c);
	};
	walk(section);
	return map;
}

/** Ayahs (ordered, de-duped) cited by footnote marks inside one top-level block,
 *  keeping only those we have generated audio for. */
function versesInBlock(
	block: HastNode,
	fnMap: Map<string, { ayahKey: string; refName: string }>,
): { ayahKey: string; refName: string }[] {
	const out: { ayahKey: string; refName: string }[] = [];
	const seen = new Set<string>();
	const walk = (node: HastNode): void => {
		if (isElement(node) && node.tagName === "a" && "dataFootnoteRef" in node.properties) {
			const href = node.properties.href;
			const id = typeof href === "string" ? href.replace(/^#/, "") : "";
			const cite = fnMap.get(id);
			if (cite && VERSES[cite.ayahKey] && !seen.has(cite.ayahKey)) {
				seen.add(cite.ayahKey);
				out.push(cite);
			}
		}
		for (const c of childrenOf(node)) walk(c);
	};
	walk(block);
	return out;
}

const playIcon = (): HastElement =>
	h(
		"svg",
		{
			className: ["qv-icon-play"],
			width: 13,
			height: 13,
			viewBox: "0 0 18 18",
			fill: "currentColor",
			ariaHidden: "true",
		},
		[h("path", { d: "M4 2.5v13l11-6.5z" })],
	);

const pauseIcon = (): HastElement =>
	h(
		"svg",
		{
			className: ["qv-icon-pause"],
			width: 13,
			height: 13,
			viewBox: "0 0 18 18",
			fill: "currentColor",
			ariaHidden: "true",
		},
		[
			h("rect", { x: 4, y: 2, width: 3.5, height: 14, rx: 0.5 }),
			h("rect", { x: 10.5, y: 2, width: 3.5, height: 14, rx: 0.5 }),
		],
	);

function buildPlayer(ayahKey: string, refName: string): HastElement {
	const v = VERSES[ayahKey];
	const [surah, ayah] = ayahKey.split(":");
	const tokens = tokenizeArabic(v.textArabic);
	const words = tokens.map((t) =>
		t.word === null
			? h("span", { className: ["qv-waqf"] }, [text(`${t.text} `)])
			: h("span", { className: ["qv-w"], dataW: t.word }, [text(`${t.text} `)]),
	);
	const nameLabel = refName ? `${refName} ` : "";
	const cite = `Koranen · ${nameLabel}${surah}:${ayah}`;
	return h("figure", { className: ["quran-verse"] }, [
		h(
			"p",
			{
				className: ["qv-arabic"],
				dir: "rtl",
				lang: "ar",
				dataSegments: JSON.stringify(v.segments),
			},
			words,
		),
		h("div", { className: ["qv-meta"] }, [
			h(
				"button",
				{
					type: "button",
					className: ["qv-play"],
					dataAudio: v.audioFile,
					ariaLabel: `Lyssna på ${nameLabel}${surah}:${ayah}, reciterad av ${v.reciter}`,
				},
				[playIcon(), pauseIcon()],
			),
			h("span", { className: ["qv-cite", "label"] }, [text(cite)]),
		]),
	]);
}

export function rehypeQuranVerse() {
	return (tree: HastNode): void => {
		if (!("children" in tree && tree.children)) return;
		const blocks = tree.children;
		const section = blocks.find(isFootnotesSection) as HastElement | undefined;
		if (!section) return;
		const fnMap = buildFootnoteMap(section);
		if (fnMap.size === 0) return;

		const out: HastNode[] = [];
		for (const node of blocks) {
			out.push(node);
			if (node === section || !isElement(node)) continue;
			for (const { ayahKey, refName } of versesInBlock(node, fnMap)) {
				out.push(buildPlayer(ayahKey, refName));
			}
		}
		tree.children = out;
	};
}
