#!/usr/bin/env node
// Bump the app version in every file that carries it, then commit + tag — one
// command so a release never lands with the colophon at 1.0.1 while Play Store
// still sees 1.0.0.
//
// Touches (only files git tracks; android/ is gitignored and regenerated by
// `expo prebuild` from app.json on every build):
//   • package.json                       — `version` (npm/git-tag convention)
//   • app.json `expo.version`            — what `Constants.expoConfig.version`
//                                          reads → the colophon on Inställningar
//                                          AND what prebuild writes to
//                                          android/.../build.gradle versionName
//   • app.json `expo.ios.buildNumber`    — App Store requires a unique string
//                                          per upload; bumped by +1 each release
//   • app.json `expo.android.versionCode` — Play Store requires a monotonically
//                                          increasing integer per uploaded
//                                          build; bumped by +1 each release.
//                                          Prebuild writes this to build.gradle.
//
// Usage:
//   pnpm release patch    1.0.0 → 1.0.1
//   pnpm release minor    1.0.0 → 1.1.0
//   pnpm release major    1.0.0 → 2.0.0
//   pnpm release 1.2.3    explicit (rare — for hotfix versioning oddities)
//
// Refuses to run if the working tree is dirty (the bump commit must be clean,
// otherwise unrelated WIP rides into a release tag). Override with --force
// only if you know what you're doing.
//
// Never auto-pushes — prints the `git push --follow-tags` line at the end so
// the developer reviews the commit + tag before publishing.

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const PKG = path.join(ROOT, 'package.json');
const APP = path.join(ROOT, 'app.json');

function read(p) {
  return fs.readFileSync(p, 'utf8');
}
function writeJson(p, obj) {
  fs.writeFileSync(p, `${JSON.stringify(obj, null, 2)}\n`);
}

function nextVersion(current, bump) {
  if (/^\d+\.\d+\.\d+$/.test(bump)) return bump;
  const [maj, min, pat] = current.split('.').map(Number);
  if (bump === 'patch') return `${maj}.${min}.${pat + 1}`;
  if (bump === 'minor') return `${maj}.${min + 1}.0`;
  if (bump === 'major') return `${maj + 1}.0.0`;
  throw new Error(`Unknown bump "${bump}" — use patch | minor | major | <X.Y.Z>`);
}

function main() {
  const [, , arg, ...rest] = process.argv;
  if (!arg) {
    console.error('usage: pnpm release <patch|minor|major|X.Y.Z> [--force]');
    process.exit(1);
  }
  const force = rest.includes('--force');

  // Refuse to bump on top of WIP inside apps/mobile — a release commit must
  // be small and pure. Scoped with `.` so unrelated WIP elsewhere in the
  // monorepo (apps/cli, packages/*) does NOT block a mobile release.
  const dirty = execSync('git status --porcelain .', { cwd: ROOT }).toString().trim();
  if (dirty && !force) {
    console.error('error: apps/mobile working tree is dirty. Commit or stash first, or pass --force.');
    console.error(dirty);
    process.exit(1);
  }

  const pkg = JSON.parse(read(PKG));
  const app = JSON.parse(read(APP));

  const current = pkg.version;
  const next = nextVersion(current, arg);
  if (next === current) {
    console.error(`error: version is already ${current}`);
    process.exit(1);
  }
  const newAndroidCode = Number(app.expo.android?.versionCode ?? 0) + 1;
  const newIosBuild = String(Number(app.expo.ios?.buildNumber ?? 0) + 1);

  // 1. package.json
  pkg.version = next;
  writeJson(PKG, pkg);

  // 2. app.json — version + native build counters. This is the single source
  // of truth: prebuild writes these into android/.../build.gradle and the
  // iOS Info.plist on every build.
  app.expo.version = next;
  app.expo.ios = app.expo.ios ?? {};
  app.expo.ios.buildNumber = newIosBuild;
  app.expo.android = app.expo.android ?? {};
  app.expo.android.versionCode = newAndroidCode;
  writeJson(APP, app);

  // 3. commit + tag (no push — developer reviews first)
  const tag = `v${next}`;
  const msg = `chore: bump version to ${tag}`;
  execSync(`git add package.json app.json`, { cwd: ROOT, stdio: 'inherit' });
  execSync(`git commit -m ${JSON.stringify(msg)}`, { cwd: ROOT, stdio: 'inherit' });
  execSync(`git tag ${tag}`, { cwd: ROOT, stdio: 'inherit' });

  console.log(`\n✓ ${current} → ${next}`);
  console.log(`  package.json    ${next}`);
  console.log(`  app.json        version ${next}, ios.buildNumber ${newIosBuild}, android.versionCode ${newAndroidCode}`);
  console.log(`  git tag         ${tag}`);
  console.log(`\nNext: git push --follow-tags`);
  console.log(`      pnpm android      # next build picks up versionCode ${newAndroidCode} via prebuild`);
}

try {
  main();
} catch (err) {
  console.error(`error: ${err.message}`);
  process.exit(1);
}
